name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  package:
    runs-on: windows-2022   # or windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package artifact (zip)
        shell: pwsh
        run: |
          Compress-Archive -Path scripts/WindowsFreezeTune.ps1, README.md, LICENSE `
            -DestinationPath windows-freeze-tune.zip -Force
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-freeze-tune
          path: windows-freeze-tune.zip
