name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}        # ← adds the “Run workflow” button
  push:
    tags:
      - 'v*.*.*'               # tag like v0.1.0 to trigger the release job

jobs:
  lint:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh            # default to PowerShell 7 for all run: steps
    steps:
      - uses: actions/checkout@v4

      - name: Trust PSGallery and install PSScriptAnalyzer
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Scope CurrentUser -Force

      - name: Lint scripts
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -EnableExit

  test:
    needs: lint
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - name: Smoke test (does the script parse & show help?)
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          .\scripts\WindowsFreezeTune.ps1 -? | Out-String | Out-Null

  package:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          Compress-Archive -Path README.md, LICENSE, scripts `
            -DestinationPath windows-freeze-tune.zip -Force

      - name: SHA256 checksum
        run: |
          $h = (Get-FileHash windows-freeze-tune.zip -Algorithm SHA256).Hash.ToLower()
          "$h  windows-freeze-tune.zip" | Out-File -Encoding ascii windows-freeze-tune.zip.sha256

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-freeze-tune.zip
            windows-freeze-tune.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
